# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl gnupg ca-certificates libnss3 libatk-bridge2.0-0 libx11-6 libx11-xcb1 \
    libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango-1.0-0 libasound2 \
    libatk1.0-0 libgtk-3-0 && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml main.py uv.lock ./
COPY README.md LICENSE ./

# Install Python dependencies
RUN pip install --no-cache-dir .
# Install Playwright and browsers
RUN pip install --no-cache-dir playwright && playwright install chromium

# Default command
CMD ["python", "main.py"]
